### ISSUE TITLE
Death of TotalTerminal

### ISSUE THREAD

**Issue by curiouscrusher** [joeyhoer/starter#3]
Since early betas of OSX El Cap TotalTerminal hasn't launched correctly. After a lot of digging around it was eventually discovered that the new Rootless Protection was hindering TotalTerminal from running correctly. As it's no longer under development, and not natively supported in El Cap, it could be time to remove it from the Cask File application list.
Have you considered replacing it with iTerm2? It doesn't have the great visor functionality that TotalTerminal offered, but it comes close with the hotkey hiding feature. Another option would be to investigate including the disabling of Rootless Protection in Starter. 
Thoughts?

**Comment by joeyhoer** [comment]
@curiouscrusher I have some included some information on disabling SIP in  https://github.com/joeyhoer/starter/blob/ff50ba9ea7e68b489957eb2066bbb0a7d6d0921a/apps/total-terminal.sh … TotalTerminal _does_ appear to be working in Sierra with SIP disables, but I'll likely be switching to iTerm when version 3 is released.
