### ISSUE TITLE
typos in apps/safari.sh

### ISSUE THREAD

**Issue by relikd** [joeyhoer/starter#5]
line 13: "Srtart"
line 32: "-stirng"
line 80; "-boot"

.. also. This doesn't seem to work anymore:
defaults write com.apple.Safari ProxiesInBookmarksBar '()'

**Comment by joeyhoer** [comment]
Thanks for the heads up. The typos are fixed; I haven't confirmed the `ProxiesInBookmarksBar` comment, but I would not be surprised. It seems that more than a few options have been deprecated.
