### ISSUE TITLE
macOS configuration compared to Migration Assistant

### ISSUE THREAD

**Issue by chrisothal** [joeyhoer/starter#9]
I have a (seemingly ignorant) question. How does this setup compare to OS X's Migration Assistant assuming you are perfectly happy with your current machine setup? Is there a particular reason you prefer having a scripted setup?

**Comment by joeyhoer** [comment]
I prefer setting up a machine from a clean slate. There is also an advantage of resetting preferences on a machine that's been modified. I also suggest checking out [mackup](https://github.com/lra/mackup)
